#Problem 2


#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def find_fib_even_sum(n)
  a,b,sum,t = 1,2,0,2
  while t < n
  	t = a + b
  	a = b
  	b = t
  	sum = sum + a if a % 2 == 0
  end
  sum
end

puts "sum below 100: #{find_fib_even_sum(100)}"
puts "sum below 4000000: #{find_fib_even_sum(4000000)}"