=begin

Problem 12


The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

=end

def divi_ct(n)
  i = 2
  f = n
  ct = 2
  while i < f
  	f,r = n.divmod(i)
  	i = i + 1
  	ct = ct + 2 if r == 0
  end
  ct
end

i = 1
tr = 0
while divi_ct( tr = (i.times.map{|x| x+1}.reduce(&:+))) < 500
	i = i + 1
end
puts tr